spring.application.name=univers_backend

server.port=8080

#Database Connection
spring.datasource.url = jdbc:mysql://localhost:3306/univers
spring.datasource.username = root
spring.datasource.password = Lordmarkpapa25!

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update 
#should change update to validate when production

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.error.include-stacktrace=never

mailjet.api.key=${MAILJET_API_KEY}
mailjet.api.secret=${MAILJET_API_SECRET}
mailjet.sender.email=${MAILJET_SENDER_EMAIL}
mailjet.template.id=${MAILJET_TEMPLATE_ID}
mailjet.template.id.forgot.password=${MAILJET_TEMPLATE_ID_FORGOT_PASSWORD}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

minio.endpoint=${MINIO_ENDPOINT:http://127.0.0.1:9000}
minio.accessKey=${MINIO_ACCESS_KEY}
minio.secretKey=${MINIO_SECRET_KEY}

minio.bucketName=univers-storage
minio.bucket.venues=univers-venues
minio.bucket.users=univers-users
minio.bucket.equipments=univers-equipments
minio.bucket.events=univers-events
minio.bucket.event_images=univers-event-images
minio.bucket.approved_letters=univers-approved-letters

cors.allowed.origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}
